# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='tally',
            field=models.IntegerField(default=0),
        ),
    ]
