# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-08 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedbot', '0003_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('subject', models.CharField(default='Chatbot user assistance', max_length=50)),
                ('body', models.CharField(max_length=300)),
            ],
        ),
    ]
