# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedbot', '0004_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tally',
            field=models.IntegerField(default=0),
        ),
    ]
