# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedbot', '0006_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regisrationnumber', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=50)),
            ],
        ),
    ]
