# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedbot', '0007_graduand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Graduand',
        ),
        migrations.AddField(
            model_name='answer',
            name='about',
            field=models.CharField(default='chat', max_length=100),
        ),
    ]
