# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedbot', '0009_unable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=200)),
                ('response', models.CharField(max_length=600)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
